### ISSUE TITLE
Add ShareDB to benchmark comparison

### ISSUE THREAD

**Issue by GermanJablo** [dmonad/crdt-benchmarks#13]
**Is your feature request related to a problem? Please describe.**
For those who are not interested in having a descentralized P2P model, the biggest impediment to choosing yjs is the performance loss that there **may** be compared to OT.

**Describe the solution you'd like**
It would be great to add ShareDB to the benchmark comparison.

**Additional context**
- I think there are more people deliberating whether to use yjs vs ShareDB than yjs vs automerge for example.
- I know it might be a bit of bad press for yjs if it turns out that it loses in the comparison. But even so, it would be understood that it is not an apples to apples comparison. In my situation, I would choose yjs even if it is a bit slower.

**Comment by dmonad** [comment]
I'm not adding ShareDB to these benchmarks because it requires a server to do transformations (also, it's just a bit massive for these benchmarks).

However, there are already benchmarks for an OT framework: https://github.com/dmonad/crdt-benchmarks/pull/7

By now, these are already outdated. But it provides a rough comparison.
